import copytrade_config as cfg
print(f"ENABLE_QUICKNODE_FEED: {cfg.ENABLE_QUICKNODE_FEED}")
print(f"QUICKNODE_SHADOW_ONLY: {cfg.QUICKNODE_SHADOW_ONLY}")
print(f"QUICKNODE_LIVE_ENABLED: {cfg.QUICKNODE_LIVE_ENABLED}")
